### ISSUE TITLE
关于安装选择太拥挤

### ISSUE THREAD

**Issue by ghost** [yeyingorg/bbr2.sh#1]
你好，你的代码在选择安装的时候  我觉得太拥挤了 你可以在调整一下  谢谢

**Comment by Anankke** [comment]
又不是不能用.webp

**Comment by yeyingorg** [comment]
这怎么就一年过去了啊
我刚才找回这个账号的密码(不是
其实早就不鼓励用bbr2了，早就不更新了。(((
